robot: 'wx250s'
collision_spheres:
  wx250s_base_link:
    - "center": [-0.013, 0.01, 0.035]
      "radius": 0.044
    - "center": [0.014, -0.011, 0.035]
      "radius": 0.043
    - "center": [-0.007, -0.017, 0.034]
      "radius": 0.044
    - "center": [0.009, 0.018, 0.033]
      "radius": 0.042
    - "center": [-0.118, 0.011, 0.019]
      "radius": 0.028
    - "center": [-0.081, -0.011, 0.019]
      "radius": 0.028
    - "center": [-0.134, -0.021, 0.019]
      "radius": 0.028
    - "center": [-0.089, 0.023, 0.018]
      "radius": 0.028
    - "center": [-0.137, 0.017, 0.017]
      "radius": 0.027
    - "center": [-0.112, -0.018, 0.019]
      "radius": 0.028
    - "center": [-0.076, -0.023, 0.019]
      "radius": 0.028
    - "center": [-0.021, -0.008, 0.03]
      "radius": 0.04
    - "center": [0.021, 0.008, 0.039]
      "radius": 0.04
    - "center": [-0.075, 0.021, 0.017]
      "radius": 0.027
    - "center": [-0.005, 0.023, 0.041]
      "radius": 0.038
    - "center": [0.031, 0.002, 0.021]
      "radius": 0.031
    - "center": [-0.028, -0.006, 0.047]
      "radius": 0.032
    - "center": [-0.027, 0.011, 0.025]
      "radius": 0.034
    - "center": [-0.006, 0.033, 0.019]
      "radius": 0.028
    - "center": [0.013, -0.03, 0.024]
      "radius": 0.031
  wx250s_shoulder_link:
    - "center": [-0.0, -0.032, 0.025]
      "radius": 0.024
    - "center": [0.0, 0.035, 0.035]
      "radius": 0.024
    - "center": [0.0, 0.03, 0.019]
      "radius": 0.024
    - "center": [-0.001, -0.035, 0.036]
      "radius": 0.023
  wx250s_upper_arm_link:
    - "center": [0.026, 0.03, 0.25]
      "radius": 0.019
    - "center": [0.03, -0.032, 0.25]
      "radius": 0.019
    - "center": [-0.0, -0.0, 0.035]
      "radius": 0.019
    - "center": [0.047, 0.033, 0.249]
      "radius": 0.018
    - "center": [0.0, -0.002, 0.232]
      "radius": 0.016
    - "center": [-0.0, -0.0, 0.068]
      "radius": 0.014
    - "center": [0.048, -0.033, 0.252]
      "radius": 0.018
    - "center": [-0.0, 0.0, 0.108]
      "radius": 0.014
    - "center": [0.0, -0.0, 0.171]
      "radius": 0.014
    - "center": [-0.002, 0.0, 0.018]
      "radius": 0.017
    - "center": [0.0, 0.0, 0.201]
      "radius": 0.014
    - "center": [0.0, -0.0, 0.085]
      "radius": 0.014
    - "center": [0.002, -0.002, 0.137]
      "radius": 0.013
    - "center": [0.001, -0.001, 0.243]
      "radius": 0.016
    - "center": [-0.001, 0.001, 0.158]
      "radius": 0.014
    - "center": [0.022, -0.037, 0.25]
      "radius": 0.018
    - "center": [0.049, -0.025, 0.248]
      "radius": 0.016
    - "center": [0.048, 0.038, 0.252]
      "radius": 0.017
    - "center": [-0.001, 0.001, 0.185]
      "radius": 0.014
    - "center": [-0.001, -0.001, 0.214]
      "radius": 0.014
    - "center": [-0.002, 0.002, 0.046]
      "radius": 0.017
    - "center": [0.051, 0.025, 0.254]
      "radius": 0.015
    - "center": [0.023, 0.036, 0.252]
      "radius": 0.018
    - "center": [-0.002, 0.002, 0.123]
      "radius": 0.013
    - "center": [0.016, 0.022, 0.227]
      "radius": 0.01
    - "center": [0.016, -0.007, 0.221]
      "radius": 0.01
    - "center": [0.05, -0.038, 0.249]
      "radius": 0.016
    - "center": [0.017, 0.043, 0.232]
      "radius": 0.01
    - "center": [0.016, 0.007, 0.226]
      "radius": 0.01
    - "center": [0.0, -0.0, 0.098]
      "radius": 0.014
  wx250s_upper_forearm_link:
    - "center": [0.149, -0.0, 0.001]
      "radius": 0.018
    - "center": [0.02, 0.001, -0.001]
      "radius": 0.018
    - "center": [0.04, -0.001, -0.002]
      "radius": 0.018
    - "center": [0.1, 0.0, 0.0]
      "radius": 0.014
    - "center": [0.118, -0.0, 0.0]
      "radius": 0.014
    - "center": [0.07, 0.001, -0.001]
      "radius": 0.014
    - "center": [0.046, 0.002, 0.003]
      "radius": 0.016
    - "center": [0.093, 0.0, -0.0]
      "radius": 0.014
    - "center": [0.144, 0.002, -0.003]
      "radius": 0.016
    - "center": [0.163, 0.006, 0.008]
      "radius": 0.011
    - "center": [0.163, 0.007, -0.008]
      "radius": 0.011
    - "center": [0.055, -0.001, -0.001]
      "radius": 0.014
    - "center": [0.028, -0.003, 0.003]
      "radius": 0.016
    - "center": [0.046, 0.004, -0.005]
      "radius": 0.014
    - "center": [0.155, -0.004, -0.004]
      "radius": 0.014
    - "center": [0.005, 0.009, -0.01]
      "radius": 0.01
    - "center": [0.006, -0.005, 0.01]
      "radius": 0.01
    - "center": [0.077, -0.001, -0.001]
      "radius": 0.014
    - "center": [-0.009, 0.008, 0.004]
      "radius": 0.009
    - "center": [0.002, -0.01, -0.01]
      "radius": 0.009
    - "center": [0.012, 0.006, 0.007]
      "radius": 0.012
    - "center": [-0.006, 0.003, -0.008]
      "radius": 0.009
    - "center": [0.03, 0.002, -0.003]
      "radius": 0.017
    - "center": [-0.009, -0.003, 0.006]
      "radius": 0.009
    - "center": [0.133, -0.003, 0.004]
      "radius": 0.011
    - "center": [-0.007, -0.008, -0.007]
      "radius": 0.009
    - "center": [0.043, -0.003, 0.003]
      "radius": 0.016
    - "center": [0.017, -0.004, 0.004]
      "radius": 0.015
    - "center": [0.153, 0.002, 0.001]
      "radius": 0.017
    - "center": [0.016, -0.008, -0.008]
      "radius": 0.011
  wx250s_lower_forearm_link:
    - "center": [0.019, 0.005, -0.0]
      "radius": 0.019
    - "center": [0.057, 0.002, 0.0]
      "radius": 0.019
    - "center": [0.017, 0.021, 0.0]
      "radius": 0.019
    - "center": [0.071, -0.004, -0.0]
      "radius": 0.019
    - "center": [0.053, -0.004, 0.0]
      "radius": 0.018
    - "center": [0.014, 0.002, 0.001]
      "radius": 0.018
    - "center": [0.023, 0.022, -0.001]
      "radius": 0.018
    - "center": [0.074, 0.003, 0.002]
      "radius": 0.017
    - "center": [0.052, 0.005, -0.002]
      "radius": 0.017
    - "center": [0.022, 0.002, -0.0]
      "radius": 0.018
  wx250s_wrist_link:
    - "center": [0.046, -0.0, 0.019]
      "radius": 0.021
    - "center": [0.042, -0.001, 0.004]
      "radius": 0.018
    - "center": [0.053, 0.002, 0.0]
      "radius": 0.017
    - "center": [0.046, 0.013, 0.01]
      "radius": 0.014
    - "center": [0.053, -0.003, 0.001]
      "radius": 0.017
    - "center": [0.045, -0.014, 0.012]
      "radius": 0.013
  wx250s_gripper_link:
    - "center": [0.028, 0.0, 0.006]
      "radius": 0.015
    - "center": [0.015, -0.0, 0.017]
      "radius": 0.015
    - "center": [0.029, -0.0, 0.019]
      "radius": 0.015
    - "center": [0.014, 0.0, 0.004]
      "radius": 0.015
    - "center": [0.012, 0.002, 0.022]
      "radius": 0.013
    - "center": [0.031, -0.003, 0.0]
      "radius": 0.012
    - "center": [0.011, -0.004, 0.025]
      "radius": 0.011
    - "center": [0.036, 0.007, -0.004]
      "radius": 0.008
    - "center": [0.033, 0.006, 0.027]
      "radius": 0.009
    - "center": [0.007, -0.007, -0.004]
      "radius": 0.008
    - "center": [0.034, -0.007, 0.028]
      "radius": 0.008
    - "center": [0.022, -0.0, 0.003]
      "radius": 0.015
    - "center": [0.025, 0.0, 0.022]
      "radius": 0.014
    - "center": [0.007, 0.006, -0.004]
      "radius": 0.008
    - "center": [0.032, -0.003, 0.011]
      "radius": 0.012
    - "center": [0.037, -0.008, -0.006]
      "radius": 0.006
    - "center": [0.034, 0.005, 0.012]
      "radius": 0.01
    - "center": [0.008, 0.006, 0.012]
      "radius": 0.009
    - "center": [0.023, -0.006, 0.027]
      "radius": 0.009
    - "center": [0.007, -0.008, 0.007]
      "radius": 0.008
    - "center": [0.024, 0.005, -0.002]
      "radius": 0.01
    - "center": [0.02, 0.008, 0.029]
      "radius": 0.008
    - "center": [0.017, -0.007, -0.004]
      "radius": 0.008
    - "center": [0.008, -0.006, 0.017]
      "radius": 0.009
    - "center": [0.035, -0.006, 0.021]
      "radius": 0.009
  wx250s_left_finger_link:
    - "center": [0.007, -0.0, -0.009]
      "radius": 0.01
    - "center": [0.0, -0.003, 0.009]
      "radius": 0.009
    - "center": [0.009, 0.001, 0.01]
      "radius": 0.009
    - "center": [-0.004, -0.001, -0.011]
      "radius": 0.009
    - "center": [0.008, -0.004, -0.009]
      "radius": 0.01
    - "center": [-0.003, -0.001, 0.01]
      "radius": 0.009
    - "center": [0.008, -0.006, 0.001]
      "radius": 0.008
    - "center": [0.002, -0.003, -0.009]
      "radius": 0.009
    - "center": [0.01, -0.006, 0.011]
      "radius": 0.008
    - "center": [-0.009, 0.0, 0.0]
      "radius": 0.008
    - "center": [0.003, 0.0, 0.01]
      "radius": 0.009
    - "center": [0.008, -0.006, 0.005]
      "radius": 0.008
    - "center": [-0.008, 0.002, 0.003]
      "radius": 0.008
    - "center": [0.009, 0.001, 0.005]
      "radius": 0.008
    - "center": [0.008, -0.006, -0.004]
      "radius": 0.008
    - "center": [-0.006, 0.001, 0.008]
      "radius": 0.008
    - "center": [0.012, 0.0, -0.011]
      "radius": 0.008
    - "center": [0.018, -0.006, 0.007]
      "radius": 0.007
    - "center": [0.033, -0.006, 0.006]
      "radius": 0.007
    - "center": [0.024, -0.004, -0.012]
      "radius": 0.007
    - "center": [0.002, 0.002, -0.012]
      "radius": 0.008
    - "center": [-0.002, -0.006, -0.008]
      "radius": 0.008
    - "center": [0.035, -0.006, 0.002]
      "radius": 0.007
    - "center": [0.021, -0.006, 0.003]
      "radius": 0.007
    - "center": [0.033, -0.003, -0.01]
      "radius": 0.007
  wx250s_right_finger_link:
    - "center": [0.008, 0.004, 0.009]
      "radius": 0.01
    - "center": [0.004, 0.001, -0.01]
      "radius": 0.009
    - "center": [-0.004, 0.001, 0.011]
      "radius": 0.009
    - "center": [-0.003, 0.001, -0.01]
      "radius": 0.009
    - "center": [0.01, 0.002, -0.01]
      "radius": 0.009
    - "center": [0.007, 0.0, 0.009]
      "radius": 0.01
    - "center": [0.008, 0.006, -0.001]
      "radius": 0.008
    - "center": [-0.009, -0.0, -0.0]
      "radius": 0.008
    - "center": [0.0, 0.002, 0.009]
      "radius": 0.009
    - "center": [0.0, 0.004, -0.01]
      "radius": 0.009
    - "center": [0.009, -0.001, -0.005]
      "radius": 0.008
    - "center": [0.008, 0.006, -0.005]
      "radius": 0.008
    - "center": [-0.002, 0.006, 0.008]
      "radius": 0.008
    - "center": [-0.008, -0.002, -0.003]
      "radius": 0.008
    - "center": [-0.006, -0.001, -0.008]
      "radius": 0.008
    - "center": [0.012, -0.0, 0.011]
      "radius": 0.008
    - "center": [0.008, 0.006, 0.004]
      "radius": 0.008
    - "center": [0.01, 0.006, -0.011]
      "radius": 0.008
    - "center": [0.009, -0.0, -0.01]
      "radius": 0.009
    - "center": [0.027, 0.002, -0.012]
      "radius": 0.007
    - "center": [0.027, 0.007, 0.009]
      "radius": 0.007
    - "center": [0.002, -0.002, 0.012]
      "radius": 0.008
    - "center": [0.04, 0.007, 0.002]
      "radius": 0.007
    - "center": [0.033, 0.007, 0.009]
      "radius": 0.007
    - "center": [0.033, 0.006, -0.006]
      "radius": 0.007